defaults: &defaults
  app_name: Catalib
  app_url: http://catalib.com/
  app_author: Luis Rubio

  valid_item_status: ['not begun', 'in progress', 'completed', 'abandoned']

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults